language: csharp
solution: Paginator.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore Paginator.sln
 
script:
  - xbuild /p:Configuration=Release Paginator.sln
  - nunit-console UnitTest\bin\Release\UnitTest.dll